// Biblical patterns (typology): an earlier person, event or institution that foreshadows a later one,
// most often Christ. Each row pairs the "shadow" (a) with its "fulfillment" (b).
// Refs use the app's OSIS-style codes; every one is checked against the NLT by scripts/check-patterns.mjs.

export const PATTERN_GROUPS = [
  'Sacrifice & Redemption',
  'People Who Point to Christ',
  'Exodus & Wilderness',
  'Tabernacle & Priesthood',
  'The Feasts',
  'Spirit & Fire',
  'Creation, Covenant & Bride',
  'Prophecy Fulfilled',
]

export const PATTERNS = [
  // ---------------- Sacrifice & Redemption ----------------
  {
    id: 'isaac',
    group: 'Sacrifice & Redemption',
    a: 'Abraham offers Isaac',
    b: 'The Father gives His Son',
    summary: 'A father offers his only, beloved son on a mountain in Moriah; the son carries the wood, and God provides the lamb. Hebrews says Abraham received Isaac back “as it were” from the dead.',
    rows: [
      { point: 'The only, beloved son', a: ['Gen.22.2'], b: ['John.3.16', 'Matt.3.17'] },
      { point: 'The son carries the wood up the hill', a: ['Gen.22.6'], b: ['John.19.17'] },
      { point: '“God will provide a lamb”', a: ['Gen.22.7-8'], b: ['John.1.29'] },
      { point: 'The son lays himself on the altar', a: ['Gen.22.9'], b: ['John.10.17-18'] },
      { point: 'A substitute dies in his place', a: ['Gen.22.13'], b: ['Mark.10.45', '1Pet.3.18'] },
      { point: 'Received back on the third day', a: ['Gen.22.4', 'Heb.11.17-19'], b: ['Luke.24.46'] },
      { point: 'Moriah, later the temple mount in Jerusalem', a: ['Gen.22.14', '2Chr.3.1'], b: ['Luke.9.31'] },
      { point: 'All nations blessed through his offspring', a: ['Gen.22.18'], b: ['Gal.3.8', 'Gal.3.16'] },
    ],
  },
  {
    id: 'passover',
    group: 'Sacrifice & Redemption',
    a: 'The Passover lamb',
    b: 'The crucifixion',
    summary: 'Israel was spared by the blood of a spotless lamb and walked out of slavery. Jesus died at Passover as “our Passover Lamb,” and His blood brings freedom.',
    rows: [
      { point: 'Lamb chosen days before the feast', a: ['Exod.12.3'], b: ['John.12.1', 'John.12.12-13'] },
      { point: 'Without defect', a: ['Exod.12.5'], b: ['1Pet.1.18-19'] },
      { point: 'Killed in the afternoon', a: ['Exod.12.6'], b: ['Mark.15.33-37'] },
      { point: 'Blood on the doorframe; death passes over', a: ['Exod.12.7', 'Exod.12.13'], b: ['1Cor.5.7', 'Rom.5.9'] },
      { point: 'Hyssop dipped in the blood', a: ['Exod.12.22'], b: ['John.19.29'] },
      { point: 'Not one bone broken', a: ['Exod.12.46'], b: ['John.19.36'] },
      { point: 'Eat the lamb with unleavened bread', a: ['Exod.12.8'], b: ['Luke.22.19-20', 'John.6.53-56'] },
      { point: 'Freedom from slavery', a: ['Exod.12.31'], b: ['John.8.36', 'Col.1.13'] },
    ],
  },
  {
    id: 'atonement',
    group: 'Sacrifice & Redemption',
    a: 'The Day of Atonement',
    b: 'Christ enters the true Most Holy Place',
    summary: 'Once a year the high priest brought blood behind the curtain, and a second goat carried the people’s sins away. Christ entered heaven itself once for all with His own blood.',
    rows: [
      { point: 'Once a year, with blood, behind the curtain', a: ['Lev.16.2', 'Lev.16.15'], b: ['Heb.9.7', 'Heb.9.11-12'] },
      { point: 'The scapegoat carries sins away', a: ['Lev.16.21-22'], b: ['Isa.53.6', 'John.1.29'] },
      { point: 'Burned outside the camp', a: ['Lev.16.27'], b: ['Heb.13.11-12'] },
      { point: 'The curtain kept the people out', a: ['Lev.16.2'], b: ['Matt.27.51', 'Heb.10.19-20'] },
      { point: 'Cleansed from all sins', a: ['Lev.16.30'], b: ['Heb.10.14', '1John.1.7'] },
      { point: 'Repeated every year vs. once for all', a: ['Lev.16.34'], b: ['Heb.10.11-12'] },
    ],
  },
  {
    id: 'serpent',
    group: 'Sacrifice & Redemption',
    a: 'The bronze serpent',
    b: 'The Son of Man lifted up',
    summary: 'Bitten Israelites who looked at the bronze snake on a pole lived. Jesus said He must be lifted up the same way, so that everyone who believes would live.',
    rows: [
      { point: 'Dying from the serpent’s bite', a: ['Num.21.6'], b: ['Rom.6.23'] },
      { point: 'Lifted up on a pole', a: ['Num.21.8'], b: ['John.3.14-15'] },
      { point: 'Look and live', a: ['Num.21.9'], b: ['John.12.32', 'Isa.45.22'] },
      { point: 'The image of the curse becomes the cure', a: ['Num.21.8-9'], b: ['2Cor.5.21', 'Gal.3.13'] },
    ],
  },
  {
    id: 'heifer',
    group: 'Sacrifice & Redemption',
    a: 'The red heifer',
    b: 'Cleansed by Christ’s blood',
    summary: 'The ashes of a spotless red heifer, slaughtered outside the camp, purified the unclean. Hebrews argues that Christ’s blood cleanses far more: the conscience.',
    rows: [
      { point: 'Without defect, never yoked', a: ['Num.19.2'], b: ['Heb.9.14'] },
      { point: 'Slaughtered outside the camp', a: ['Num.19.3'], b: ['Heb.13.12'] },
      { point: 'Water of purification', a: ['Num.19.9'], b: ['Heb.9.13-14', 'Heb.10.22'] },
    ],
  },
  {
    id: 'two-birds',
    group: 'Sacrifice & Redemption',
    a: 'The two birds of cleansing',
    b: 'Death and resurrection',
    summary: 'To declare a leper clean, one bird was killed over running water and the living bird, dipped in its blood, was set free into the open sky.',
    rows: [
      { point: 'One bird killed over running water', a: ['Lev.14.4-5'], b: ['1Pet.3.18'] },
      { point: 'The living bird dipped in blood and released', a: ['Lev.14.6-7'], b: ['Rom.4.25', 'Rev.1.18'] },
      { point: 'The leper declared clean', a: ['Lev.14.7'], b: ['Matt.8.2-3', '1John.1.9'] },
    ],
  },
  {
    id: 'sacrifices',
    group: 'Sacrifice & Redemption',
    a: 'The offerings of Leviticus',
    b: 'The one sacrifice of Christ',
    summary: 'Burnt, sin, guilt and peace offerings each pictured part of what the cross would accomplish once for all.',
    rows: [
      { point: 'Life is in the blood', a: ['Lev.17.11'], b: ['Heb.9.22', 'Eph.1.7'] },
      { point: 'Burnt offering: wholly given, a pleasing aroma', a: ['Lev.1.3-4', 'Lev.1.9'], b: ['Eph.5.2'] },
      { point: 'Sin offering', a: ['Lev.4.27-29'], b: ['2Cor.5.21', 'Heb.13.11-12'] },
      { point: 'Guilt offering', a: ['Lev.5.15'], b: ['Isa.53.10'] },
      { point: 'Peace offering', a: ['Lev.3.1'], b: ['Col.1.20', 'Eph.2.14'] },
      { point: 'Many sacrifices vs. one', a: ['Heb.10.1-4'], b: ['Heb.10.10', 'Heb.10.14'] },
    ],
  },
  {
    id: 'lamb',
    group: 'Sacrifice & Redemption',
    a: 'The lamb through Scripture',
    b: 'The Lamb on the throne',
    summary: 'The lamb is promised to Abraham, slain at Passover, silent before its shearers in Isaiah, named by John the Baptist, and worshiped on the throne in Revelation.',
    rows: [
      { point: '“God will provide a lamb”', a: ['Gen.22.8'], b: ['John.1.29'] },
      { point: 'The Passover lamb', a: ['Exod.12.3', 'Exod.12.13'], b: ['1Cor.5.7'] },
      { point: 'Led like a lamb to the slaughter', a: ['Isa.53.7'], b: ['Acts.8.32-35'] },
      { point: 'The Lamb who was slain is worthy', a: ['Rev.5.6'], b: ['Rev.5.12'] },
      { point: 'The Lamb is the light of the city', a: ['Isa.60.19'], b: ['Rev.21.23'] },
    ],
  },
  {
    id: 'cain-abel',
    group: 'Sacrifice & Redemption',
    a: 'Abel’s blood',
    b: 'The blood that speaks a better word',
    summary: 'Abel offered by faith and was murdered by his brother; his blood cried out from the ground. Jesus’ blood speaks of forgiveness instead of vengeance.',
    rows: [
      { point: 'An offering accepted by faith', a: ['Gen.4.4'], b: ['Heb.11.4'] },
      { point: 'Killed by his own brother', a: ['Gen.4.8'], b: ['1John.3.12', 'Matt.23.35'] },
      { point: 'Blood that cries out', a: ['Gen.4.10'], b: ['Heb.12.24'] },
    ],
  },

  // ---------------- People Who Point to Christ ----------------
  {
    id: 'adam',
    group: 'People Who Point to Christ',
    a: 'Adam',
    b: 'Christ, the last Adam',
    summary: 'Paul calls Adam “a symbol, a representation of Christ.” One man’s disobedience brought death; one man’s obedience brings life.',
    rows: [
      { point: 'Made in God’s image', a: ['Gen.1.26-27'], b: ['Col.1.15', 'Heb.1.3'] },
      { point: 'A living person vs. a life-giving Spirit', a: ['Gen.2.7'], b: ['1Cor.15.45'] },
      { point: 'A bride taken from his side while he slept', a: ['Gen.2.21-22'], b: ['John.19.34', 'Eph.5.31-32'] },
      { point: 'Disobedience vs. obedience', a: ['Gen.3.6'], b: ['Rom.5.19'] },
      { point: 'Death through one; life through one', a: ['Gen.3.17-19'], b: ['Rom.5.12', '1Cor.15.21-22'] },
      { point: 'Thorns: the sign of the curse', a: ['Gen.3.18'], b: ['Matt.27.29'] },
      { point: 'A garden', a: ['Gen.2.15'], b: ['John.18.1', 'John.19.41'] },
      { point: 'Adam a type of the one to come', a: ['Gen.2.16-17'], b: ['Rom.5.14'] },
    ],
  },
  {
    id: 'jacob-blessing',
    group: 'People Who Point to Christ',
    a: 'Jacob receives the firstborn’s blessing',
    b: 'Clothed in Christ',
    summary: 'Jacob came to his father wearing his elder brother’s clothes and received the firstborn’s blessing. The gospel offers something better and honest: we are clothed in Christ, the true Firstborn, and receive every blessing in Him.',
    rows: [
      { point: 'Clothed in the elder brother’s garments', a: ['Gen.27.15-16'], b: ['Gal.3.27', 'Rom.13.14'] },
      { point: 'The fragrance of the garments', a: ['Gen.27.27'], b: ['2Cor.2.15', 'Eph.5.2'] },
      { point: 'Blessed as the firstborn', a: ['Gen.27.19', 'Gen.27.28-29'], b: ['Heb.12.23', 'Eph.1.3'] },
      { point: 'The older will serve the younger', a: ['Gen.25.23'], b: ['Rom.9.10-12'] },
      { point: 'Esau despised the birthright', a: ['Gen.25.31-34'], b: ['Heb.12.16-17'] },
      { point: 'The blessing of Abraham comes to us', a: ['Gen.28.3-4'], b: ['Gal.3.14'] },
    ],
  },
  {
    id: 'skins',
    group: 'People Who Point to Christ',
    a: 'Garments of skin',
    b: 'The robe of righteousness',
    summary: 'Fig leaves could not cover Adam and Eve; God clothed them with skins, which meant a death. Scripture keeps returning to God replacing filthy clothes with clean ones.',
    rows: [
      { point: 'Fig leaves: covering ourselves', a: ['Gen.3.7'], b: ['Isa.64.6', 'Eph.2.8-9'] },
      { point: 'God clothes them', a: ['Gen.3.21'], b: ['Gal.3.27'] },
      { point: 'Filthy clothes exchanged', a: ['Zech.3.3-5'], b: ['Luke.15.22'] },
      { point: 'Dressed in salvation', a: ['Isa.61.10'], b: ['Rev.7.14', 'Rev.19.8'] },
    ],
  },
  {
    id: 'joseph',
    group: 'People Who Point to Christ',
    a: 'Joseph',
    b: 'Jesus',
    summary: 'The favored son, rejected by his brothers and sold for silver, suffers unjustly, is raised to the right hand of the throne, feeds the world, and forgives those who betrayed him.',
    rows: [
      { point: 'Beloved son of his father', a: ['Gen.37.3'], b: ['Matt.3.17'] },
      { point: 'Hated by his brothers', a: ['Gen.37.4', 'Gen.37.8'], b: ['John.1.11', 'John.15.25'] },
      { point: 'Stripped of his robe', a: ['Gen.37.23'], b: ['John.19.23-24'] },
      { point: 'Sold for pieces of silver', a: ['Gen.37.28'], b: ['Matt.26.15'] },
      { point: 'Tempted, yet did not sin', a: ['Gen.39.9-12'], b: ['Heb.4.15'] },
      { point: 'Between two prisoners: one restored, one lost', a: ['Gen.40.20-22'], b: ['Luke.23.39-43'] },
      { point: 'Thirty years old when his ministry began', a: ['Gen.41.46'], b: ['Luke.3.23'] },
      { point: 'Exalted; every knee bows', a: ['Gen.41.40-43'], b: ['Phil.2.9-10'] },
      { point: 'Bread for the whole world', a: ['Gen.41.57'], b: ['John.6.35'] },
      { point: '“You meant it for evil; God meant it for good”', a: ['Gen.45.4-8', 'Gen.50.20'], b: ['Acts.2.23-24'] },
    ],
  },
  {
    id: 'moses',
    group: 'People Who Point to Christ',
    a: 'Moses',
    b: 'The Prophet like Moses',
    summary: 'Moses promised that God would raise up a prophet like him. Peter and Stephen both name Jesus as that Prophet.',
    rows: [
      { point: 'A prophet like me', a: ['Deut.18.15'], b: ['Acts.3.22', 'Acts.7.37'] },
      { point: 'Spared when a king killed the infants', a: ['Exod.1.22', 'Exod.2.2-3'], b: ['Matt.2.13-16'] },
      { point: 'Called out of Egypt', a: ['Hos.11.1'], b: ['Matt.2.15'] },
      { point: 'Rejected by his own people', a: ['Exod.2.14'], b: ['Acts.7.35'] },
      { point: 'Forty days of fasting', a: ['Exod.34.28'], b: ['Matt.4.2'] },
      { point: 'A shining face on the mountain', a: ['Exod.34.29'], b: ['Matt.17.2'] },
      { point: 'Bread from heaven', a: ['Exod.16.15'], b: ['John.6.32-35'] },
      { point: 'Mediator of a covenant in blood', a: ['Exod.24.8'], b: ['Luke.22.20', 'Heb.9.15'] },
      { point: 'Offers himself for the people', a: ['Exod.32.32'], b: ['Rom.9.3', 'Gal.3.13'] },
    ],
  },
  {
    id: 'joshua',
    group: 'People Who Point to Christ',
    a: 'Joshua',
    b: 'Jesus (Yeshua), who leads us into rest',
    summary: 'Joshua and Jesus share one Hebrew name, Yeshua, “Yahweh saves.” Joshua led Israel through the Jordan into the land; Hebrews says Jesus brings a greater rest.',
    rows: [
      { point: 'Leads the people into the inheritance', a: ['Josh.1.2-3'], b: ['Heb.4.8-10', 'Eph.1.11'] },
      { point: 'At the Jordan', a: ['Josh.3.15-17'], b: ['Matt.3.13-16'] },
      { point: 'Commander of the LORD’s army', a: ['Josh.5.13-15'], b: ['Rev.19.11-14'] },
      { point: 'Walls fall by faith', a: ['Josh.6.20'], b: ['Heb.11.30', '2Cor.10.4'] },
    ],
  },
  {
    id: 'rahab',
    group: 'People Who Point to Christ',
    a: 'Rahab’s scarlet cord',
    b: 'Saved under the blood',
    summary: 'A Canaanite woman hung a scarlet cord from her window and everyone under her roof was spared. She became an ancestor of Jesus.',
    rows: [
      { point: 'The scarlet cord in the window', a: ['Josh.2.18-19'], b: ['1Pet.1.18-19'] },
      { point: 'Saved by faith', a: ['Josh.6.25'], b: ['Heb.11.31', 'Jas.2.25'] },
      { point: 'An outsider grafted into the line of Christ', a: ['Josh.6.25'], b: ['Matt.1.5', 'Eph.2.12-13'] },
    ],
  },
  {
    id: 'boaz',
    group: 'People Who Point to Christ',
    a: 'Boaz the kinsman-redeemer',
    b: 'Christ our Redeemer',
    summary: 'Only a close relative could redeem. Boaz paid the price and took a foreign bride under his covering. Christ became our flesh-and-blood relative to redeem a people for Himself.',
    rows: [
      { point: 'A close relative', a: ['Ruth.2.1'], b: ['Heb.2.11', 'Heb.2.14'] },
      { point: 'A foreigner welcomed in', a: ['Ruth.1.16', 'Ruth.2.10'], b: ['Eph.2.12-13'] },
      { point: '“Spread the corner of your covering over me”', a: ['Ruth.3.9'], b: ['Ezek.16.8'] },
      { point: 'He pays the price to redeem', a: ['Ruth.4.9-10'], b: ['1Pet.1.18-19'] },
      { point: 'He takes her as his bride', a: ['Ruth.4.13'], b: ['Eph.5.25-27', 'Rev.19.7'] },
      { point: 'In Bethlehem, in the line of David', a: ['Ruth.4.17'], b: ['Matt.1.5-6', 'Luke.2.4'] },
    ],
  },
  {
    id: 'david',
    group: 'People Who Point to Christ',
    a: 'David',
    b: 'The Son of David',
    summary: 'The shepherd-king from Bethlehem was anointed, defeated the giant, was betrayed by a trusted friend, and received the promise of an eternal throne.',
    rows: [
      { point: 'From Bethlehem', a: ['1Sam.17.12'], b: ['Luke.2.4-11'] },
      { point: 'Anointed with the Spirit', a: ['1Sam.16.13'], b: ['Luke.3.22', 'Acts.10.38'] },
      { point: 'A shepherd', a: ['1Sam.17.34-35'], b: ['John.10.11'] },
      { point: 'Defeats the giant for the people', a: ['1Sam.17.50'], b: ['Col.2.15', 'Heb.2.14-15'] },
      { point: 'Crosses the Kidron weeping, rejected', a: ['2Sam.15.23', '2Sam.15.30'], b: ['John.18.1', 'Luke.22.44'] },
      { point: 'Betrayed by a friend who hangs himself', a: ['2Sam.17.23', 'Ps.41.9'], b: ['John.13.18', 'Matt.27.5'] },
      { point: 'A throne forever', a: ['2Sam.7.12-13'], b: ['Luke.1.32-33'] },
    ],
  },
  {
    id: 'solomon',
    group: 'People Who Point to Christ',
    a: 'Solomon',
    b: 'One greater than Solomon',
    summary: 'The son of David known for wisdom, peace and the temple. Jesus said, “someone greater than Solomon is here.”',
    rows: [
      { point: 'Wisdom', a: ['1Kgs.4.29'], b: ['Matt.12.42', 'Col.2.3'] },
      { point: 'A man of peace', a: ['1Chr.22.9'], b: ['Eph.2.14', 'Isa.9.6'] },
      { point: 'Builds God’s house', a: ['1Kgs.6.1', '2Sam.7.13'], b: ['Matt.16.18', 'Eph.2.21-22'] },
      { point: 'Gifts from foreign rulers', a: ['1Kgs.10.1-2'], b: ['Matt.2.11'] },
    ],
  },
  {
    id: 'melchizedek',
    group: 'People Who Point to Christ',
    a: 'Melchizedek',
    b: 'Christ, priest forever',
    summary: 'King of Salem and priest of God Most High, who brought out bread and wine. Hebrews shows Christ as priest “in the order of Melchizedek.”',
    rows: [
      { point: 'King of righteousness, king of peace', a: ['Gen.14.18'], b: ['Heb.7.1-2'] },
      { point: 'Bread and wine', a: ['Gen.14.18'], b: ['Luke.22.19-20'] },
      { point: 'Abraham gives him a tenth', a: ['Gen.14.20'], b: ['Heb.7.4-7'] },
      { point: 'A priest forever', a: ['Ps.110.4'], b: ['Heb.7.17', 'Heb.7.24-25'] },
    ],
  },
  {
    id: 'jonah',
    group: 'People Who Point to Christ',
    a: 'Jonah',
    b: 'The sign of Jonah',
    summary: 'Jesus named Jonah’s three days in the fish as the one sign He would give: His own death and resurrection.',
    rows: [
      { point: 'Asleep in the storm', a: ['Jonah.1.4-5'], b: ['Mark.4.37-38'] },
      { point: 'One thrown overboard so the rest are saved', a: ['Jonah.1.12', 'Jonah.1.15'], b: ['John.11.50'] },
      { point: 'Three days and three nights', a: ['Jonah.1.17'], b: ['Matt.12.40'] },
      { point: 'Brought up from the pit', a: ['Jonah.2.6'], b: ['Acts.2.24'] },
      { point: 'Repentance preached to the nations', a: ['Jonah.3.4-5'], b: ['Matt.12.41', 'Luke.24.47'] },
    ],
  },
  {
    id: 'elijah-john',
    group: 'People Who Point to Christ',
    a: 'Elijah',
    b: 'John the Baptist',
    summary: 'Malachi promised Elijah would come before the day of the LORD. Jesus said John “is Elijah, the one the prophets said would come.”',
    rows: [
      { point: 'Elijah will come first', a: ['Mal.4.5-6'], b: ['Matt.11.14', 'Luke.1.17'] },
      { point: 'Hairy cloak and leather belt', a: ['2Kgs.1.8'], b: ['Matt.3.4'] },
      { point: 'Opposed by a king and his wicked queen', a: ['1Kgs.19.2'], b: ['Mark.6.17-19'] },
      { point: 'A voice in the wilderness', a: ['Isa.40.3'], b: ['Mark.1.2-4'] },
    ],
  },
  {
    id: 'elisha',
    group: 'People Who Point to Christ',
    a: 'Elisha’s miracles',
    b: 'Jesus’ miracles',
    summary: 'Elisha fed a crowd with a few loaves, raised a son to life near Shunem, and cleansed a foreign leper. Jesus did the same, on a greater scale.',
    rows: [
      { point: 'A few loaves feed many, with some left over', a: ['2Kgs.4.42-44'], b: ['Matt.14.19-21'] },
      { point: 'A mother’s only son raised', a: ['2Kgs.4.32-35'], b: ['Luke.7.12-15'] },
      { point: 'A foreign leper cleansed', a: ['2Kgs.5.14'], b: ['Luke.4.27', 'Luke.17.15-16'] },
      { point: 'Life from contact with the dead prophet', a: ['2Kgs.13.21'], b: ['Matt.27.52-53'] },
    ],
  },
  {
    id: 'mephibosheth',
    group: 'People Who Point to Christ',
    a: 'Mephibosheth at David’s table',
    b: 'Grace for enemies',
    summary: 'Lame, from the house of David’s enemy, Mephibosheth was sought out for Jonathan’s sake and seated at the king’s table for good.',
    rows: [
      { point: 'From the enemy’s house, unable to walk', a: ['2Sam.9.3'], b: ['Rom.5.6', 'Rom.5.10'] },
      { point: 'For the sake of a covenant friend', a: ['2Sam.9.1', '2Sam.9.7'], b: ['Eph.4.32'] },
      { point: '“Who is your servant, that you should show kindness to a dead dog like me?”', a: ['2Sam.9.8'], b: ['Eph.2.4-5'] },
      { point: 'Eats at the king’s table always', a: ['2Sam.9.13'], b: ['Luke.22.29-30', 'Rev.19.9'] },
    ],
  },
  {
    id: 'esther',
    group: 'People Who Point to Christ',
    a: 'Esther',
    b: 'Christ our intercessor',
    summary: 'Esther risked death to approach the king for her people, and the enemy’s decree was overturned.',
    rows: [
      { point: 'Approaching the throne', a: ['Esth.4.16', 'Esth.5.2'], b: ['Heb.4.16'] },
      { point: 'Interceding for her people', a: ['Esth.7.3-4'], b: ['Heb.7.25', 'Rom.8.34'] },
      { point: 'The decree against them overturned', a: ['Esth.8.8'], b: ['Col.2.14'] },
      { point: 'The enemy hanged on his own gallows', a: ['Esth.7.10'], b: ['Col.2.15'] },
      { point: 'Mourning turned to joy', a: ['Esth.9.22'], b: ['John.16.20'] },
    ],
  },
  {
    id: 'hosea',
    group: 'People Who Point to Christ',
    a: 'Hosea buys back Gomer',
    b: 'God’s love for the unfaithful',
    summary: 'God told Hosea to love and buy back his unfaithful wife, as a living picture of His own love for His people.',
    rows: [
      { point: 'Love that comes first', a: ['Hos.1.2'], b: ['Rom.5.8'] },
      { point: 'Bought back with a price', a: ['Hos.3.1-2'], b: ['1Cor.6.20'] },
      { point: 'Betrothed forever', a: ['Hos.2.19-20'], b: ['Eph.5.25-27'] },
      { point: '“Not my people” become “my people”', a: ['Hos.2.23'], b: ['Rom.9.25-26', '1Pet.2.10'] },
    ],
  },

  // ---------------- Exodus & Wilderness ----------------
  {
    id: 'exodus',
    group: 'Exodus & Wilderness',
    a: 'The Exodus',
    b: 'Salvation from sin',
    summary: 'God heard His people’s cry, redeemed them with a mighty arm, and brought them out of slavery to Himself. Jesus spoke of His own “exodus” at Jerusalem.',
    rows: [
      { point: 'God hears and comes down to rescue', a: ['Exod.3.7-8'], b: ['Luke.4.18', 'Gal.4.4-5'] },
      { point: 'Redeemed with a mighty arm', a: ['Exod.6.6'], b: ['Eph.1.7', 'Titus.2.14'] },
      { point: 'Jesus’ own exodus at Jerusalem', a: ['Exod.12.41'], b: ['Luke.9.30-31'] },
      { point: 'Out of slavery into a kingdom', a: ['Exod.19.4-6'], b: ['Col.1.13', '1Pet.2.9'] },
    ],
  },
  {
    id: 'red-sea',
    group: 'Exodus & Wilderness',
    a: 'Crossing the Red Sea',
    b: 'Baptism',
    summary: 'Paul writes that Israel was “baptized as followers of Moses in the cloud and in the sea.” The old master was drowned behind them.',
    rows: [
      { point: 'Under the cloud and through the sea', a: ['Exod.13.21', 'Exod.14.21-22'], b: ['1Cor.10.1-2'] },
      { point: 'The old master drowned behind them', a: ['Exod.14.27-28'], b: ['Rom.6.3-6', 'Col.2.12'] },
      { point: 'Sins thrown into the depths', a: ['Mic.7.19'], b: ['Acts.22.16'] },
      { point: 'The song of the redeemed', a: ['Exod.15.1-2'], b: ['Rev.15.2-3'] },
    ],
  },
  {
    id: 'manna',
    group: 'Exodus & Wilderness',
    a: 'Manna in the wilderness',
    b: 'The Bread of Life',
    summary: 'God fed Israel with bread from heaven each morning. Jesus said, “I am the bread of life… whoever eats this bread will live forever.”',
    rows: [
      { point: 'Bread from heaven', a: ['Exod.16.4'], b: ['John.6.31-33'] },
      { point: '“What is it?”', a: ['Exod.16.15'], b: ['John.6.35'] },
      { point: 'Gathered daily', a: ['Exod.16.21'], b: ['Matt.6.11'] },
      { point: 'Not by bread alone', a: ['Deut.8.3'], b: ['Matt.4.4'] },
      { point: 'They ate and died vs. eat and live forever', a: ['Exod.16.35'], b: ['John.6.49-51'] },
      { point: 'Manna kept before the LORD', a: ['Exod.16.33'], b: ['Rev.2.17'] },
    ],
  },
  {
    id: 'rock',
    group: 'Exodus & Wilderness',
    a: 'Water from the rock',
    b: 'Christ struck, the Spirit poured out',
    summary: 'The rock was struck and water gushed out for the people. Paul says “that rock was Christ,” and Jesus promised rivers of living water, meaning the Spirit.',
    rows: [
      { point: 'The rock is struck', a: ['Exod.17.6'], b: ['1Cor.10.4'] },
      { point: 'Struck once, not twice', a: ['Num.20.8-11'], b: ['Heb.9.28'] },
      { point: 'Rivers of living water', a: ['Ps.78.15-16'], b: ['John.7.37-39'] },
      { point: 'Blood and water from His side', a: ['Exod.17.6'], b: ['John.19.34'] },
    ],
  },
  {
    id: 'wilderness',
    group: 'Exodus & Wilderness',
    a: 'Israel’s forty years',
    b: 'Jesus’ forty days',
    summary: 'Israel passed through the waters, then was tested forty years in the wilderness and failed. Jesus passed through the waters, was tested forty days, and answered every temptation from Deuteronomy.',
    rows: [
      { point: 'Through the water, then into the wilderness', a: ['Exod.15.22'], b: ['Matt.3.16-4.1'] },
      { point: 'Forty years / forty days of testing', a: ['Deut.8.2'], b: ['Matt.4.1-2'] },
      { point: 'Not by bread alone', a: ['Deut.8.3'], b: ['Matt.4.4'] },
      { point: 'Do not test the LORD', a: ['Deut.6.16'], b: ['Matt.4.7'] },
      { point: 'Worship the LORD only', a: ['Deut.6.13'], b: ['Matt.4.10'] },
    ],
  },
  {
    id: 'jordan',
    group: 'Exodus & Wilderness',
    a: 'Crossing the Jordan',
    b: 'Entering new life in Christ',
    summary: 'Israel crossed into the land, set up memorial stones, was circumcised at Gilgal, and ate the land’s produce as the manna stopped.',
    rows: [
      { point: 'Entering the rest', a: ['Josh.3.17'], b: ['Heb.4.8-11'] },
      { point: 'Living stones', a: ['Josh.4.8-9'], b: ['1Pet.2.5'] },
      { point: 'Circumcision at Gilgal', a: ['Josh.5.2-3'], b: ['Col.2.11-12'] },
      { point: 'The manna stops; they eat the land’s produce', a: ['Josh.5.12'], b: ['Eph.1.3'] },
    ],
  },
  {
    id: 'refuge',
    group: 'Exodus & Wilderness',
    a: 'The cities of refuge',
    b: 'Refuge in Christ',
    summary: 'Anyone fleeing the avenger could run to a city of refuge and stay safe until the death of the high priest.',
    rows: [
      { point: 'Run for refuge', a: ['Num.35.11'], b: ['Heb.6.18'] },
      { point: 'Open to the foreigner too', a: ['Num.35.15'], b: ['Eph.2.13'] },
      { point: 'Free at the high priest’s death', a: ['Num.35.25', 'Num.35.28'], b: ['Heb.9.15', 'Rom.8.1'] },
    ],
  },

  // ---------------- Tabernacle & Priesthood ----------------
  {
    id: 'tabernacle',
    group: 'Tabernacle & Priesthood',
    a: 'The Tabernacle',
    b: 'God with us in Christ',
    summary: 'The tabernacle was “a copy, a shadow of the real one in heaven.” John says the Word became flesh and “made his dwelling,” literally pitched His tent, among us.',
    rows: [
      { point: 'God dwells among His people', a: ['Exod.25.8-9'], b: ['John.1.14'] },
      { point: 'The glory fills it', a: ['Exod.40.34'], b: ['John.1.14', '2Cor.4.6'] },
      { point: 'A copy of the heavenly', a: ['Exod.25.40'], b: ['Heb.8.5', 'Heb.9.24'] },
      { point: 'One entrance', a: ['Exod.27.16'], b: ['John.10.9', 'John.14.6'] },
      { point: 'The bronze altar', a: ['Exod.27.1-2'], b: ['Heb.13.10'] },
      { point: 'The washbasin', a: ['Exod.30.18-20'], b: ['Titus.3.5', 'Eph.5.26'] },
      { point: 'The lampstand', a: ['Exod.25.31', 'Exod.25.37'], b: ['John.8.12'] },
      { point: 'The table of the Bread of the Presence', a: ['Exod.25.30'], b: ['John.6.48'] },
      { point: 'The incense altar', a: ['Exod.30.7-8'], b: ['Rev.8.3-4', 'Heb.7.25'] },
      { point: 'The curtain', a: ['Exod.26.33'], b: ['Heb.10.19-20', 'Matt.27.51'] },
      { point: 'The atonement cover (mercy seat)', a: ['Exod.25.21-22'], b: ['Rom.3.25'] },
    ],
  },
  {
    id: 'ark',
    group: 'Tabernacle & Priesthood',
    a: 'The Ark of the Covenant',
    b: 'Christ, God’s presence among us',
    summary: 'Wood overlaid with gold, holding the law, the manna and Aaron’s staff, crowned by the atonement cover where God met His people.',
    rows: [
      { point: 'Wood overlaid with gold', a: ['Exod.25.10-11'], b: ['John.1.14', 'Col.2.9'] },
      { point: 'The tablets, the manna and the staff', a: ['Heb.9.4'], b: ['Matt.5.17', 'John.6.35', 'Rom.1.4'] },
      { point: 'Blood on the atonement cover', a: ['Lev.16.14'], b: ['Rom.3.25'] },
      { point: 'Where God meets His people', a: ['Exod.25.22'], b: ['Heb.4.16'] },
      { point: 'The ark seen in heaven’s temple', a: ['Exod.25.21'], b: ['Rev.11.19'] },
    ],
  },
  {
    id: 'ark-mary',
    group: 'Tabernacle & Priesthood',
    a: 'The Ark goes to the hill country',
    b: 'Mary visits Elizabeth',
    summary: 'Luke tells Mary’s visit in language that echoes the ark’s journey: a question of unworthiness, a leap for joy, and a three-month stay in the hill country of Judah.',
    rows: [
      { point: '“How can the ark of the LORD come to me?”', a: ['2Sam.6.9'], b: ['Luke.1.43'] },
      { point: 'Leaping for joy', a: ['2Sam.6.14-16'], b: ['Luke.1.41', 'Luke.1.44'] },
      { point: 'Stays three months', a: ['2Sam.6.11'], b: ['Luke.1.56'] },
      { point: 'The household is blessed', a: ['2Sam.6.11-12'], b: ['Luke.1.41-42'] },
    ],
  },
  {
    id: 'aaron',
    group: 'Tabernacle & Priesthood',
    a: 'Aaron the high priest',
    b: 'Christ our High Priest',
    summary: 'Aaron was called by God, anointed, and carried the tribes’ names on his shoulders and heart. Christ is the sinless High Priest who lives forever to intercede.',
    rows: [
      { point: 'Called by God, not self-appointed', a: ['Exod.28.1'], b: ['Heb.5.4-5'] },
      { point: 'Names carried on shoulders and heart', a: ['Exod.28.12', 'Exod.28.29'], b: ['Heb.7.25', 'John.10.3'] },
      { point: 'Anointed', a: ['Lev.8.12'], b: ['Acts.10.38', 'Heb.1.9'] },
      { point: 'Offers for his own sins first', a: ['Lev.16.6'], b: ['Heb.7.26-27'] },
      { point: 'Dies, and the office passes on', a: ['Num.20.28'], b: ['Heb.7.23-24'] },
    ],
  },
  {
    id: 'aarons-rod',
    group: 'Tabernacle & Priesthood',
    a: 'Aaron’s staff that budded',
    b: 'The resurrection',
    summary: 'A dead stick sprouted, blossomed and produced almonds overnight, marking God’s chosen priest. Almond trees bloom first in spring, like a firstfruits.',
    rows: [
      { point: 'Life from dead wood', a: ['Num.17.8'], b: ['Rom.1.4', '1Cor.15.20'] },
      { point: 'God’s chosen priest confirmed', a: ['Num.17.5'], b: ['Heb.5.4-6'] },
      { point: 'Kept in the ark', a: ['Num.17.10', 'Heb.9.4'], b: ['Rev.1.18'] },
    ],
  },
  {
    id: 'temple',
    group: 'Tabernacle & Priesthood',
    a: 'Solomon’s temple',
    b: 'Christ’s body and His church',
    summary: 'Jesus called His body a temple. Believers are living stones built into a dwelling for God by His Spirit.',
    rows: [
      { point: 'The glory fills the house', a: ['1Kgs.8.10-11'], b: ['Acts.2.2-4', '1Cor.3.16'] },
      { point: 'The temple torn down… and raised', a: ['1Kgs.9.7-8'], b: ['John.2.19-21'] },
      { point: 'Stones shaped off-site, no hammer heard', a: ['1Kgs.6.7'], b: ['1Pet.2.5'] },
      { point: 'Something greater than the temple', a: ['Hag.2.9'], b: ['Matt.12.6'] },
      { point: 'A river flows from the temple', a: ['Ezek.47.1', 'Ezek.47.9'], b: ['John.7.38', 'Rev.22.1-2'] },
    ],
  },

  // ---------------- The Feasts ----------------
  {
    id: 'unleavened',
    group: 'The Feasts',
    a: 'The Festival of Unleavened Bread',
    b: 'A sinless sacrifice, a clean life',
    summary: 'For seven days after Passover no yeast was allowed. Paul applies it directly: Christ our Passover is sacrificed, so live without the old yeast of sin.',
    rows: [
      { point: 'Remove the yeast', a: ['Exod.12.15', 'Lev.23.6'], b: ['1Cor.5.7-8'] },
      { point: 'Bread without yeast', a: ['Exod.12.39'], b: ['Luke.22.19', '2Cor.5.21'] },
    ],
  },
  {
    id: 'firstfruits',
    group: 'The Feasts',
    a: 'The Festival of Firstfruits',
    b: 'The resurrection on the first day',
    summary: 'The first sheaf was waved before the LORD “on the day after the Sabbath.” Christ rose on that day, “the first of a great harvest.”',
    rows: [
      { point: 'The day after the Sabbath', a: ['Lev.23.10-11'], b: ['Matt.28.1', 'Mark.16.9'] },
      { point: 'The first of the harvest', a: ['Lev.23.10'], b: ['1Cor.15.20-23'] },
      { point: 'Firstfruits belong to God', a: ['Exod.23.19'], b: ['Jas.1.18', 'Rev.14.4'] },
    ],
  },
  {
    id: 'pentecost',
    group: 'The Feasts',
    a: 'The Festival of Harvest (Shavuot) and Sinai',
    b: 'Pentecost',
    summary: 'Fifty days after Passover, God came down on Sinai in fire and gave the law, and three thousand died. Fifty days after the resurrection, fire came down, the Spirit wrote the law on hearts, and three thousand were saved.',
    rows: [
      { point: 'Fifty days', a: ['Lev.23.15-16'], b: ['Acts.2.1'] },
      { point: 'Fire, smoke and a great sound', a: ['Exod.19.16-18'], b: ['Acts.2.2-3'] },
      { point: 'Law on stone vs. law on hearts', a: ['Exod.31.18', 'Jer.31.33'], b: ['2Cor.3.3', 'Heb.8.10'] },
      { point: 'Three thousand die vs. three thousand saved', a: ['Exod.32.28'], b: ['Acts.2.41'] },
      { point: 'Two loaves baked with yeast', a: ['Lev.23.17'], b: ['Eph.2.14-16'] },
      { point: 'The letter kills, the Spirit gives life', a: ['Exod.32.15-16'], b: ['2Cor.3.6'] },
    ],
  },
  {
    id: 'trumpets',
    group: 'The Feasts',
    a: 'The Festival of Trumpets',
    b: 'The return of Christ',
    summary: 'A day of trumpet blasts called the people together. The New Testament ties the last trumpet to the Lord’s return and the gathering of His people.',
    rows: [
      { point: 'A sacred day of trumpet blasts', a: ['Lev.23.24'], b: ['1Thess.4.16-17'] },
      { point: 'Trumpets gather the community', a: ['Num.10.2-3'], b: ['Matt.24.31'] },
      { point: 'At the last trumpet', a: ['Joel.2.1'], b: ['1Cor.15.51-52'] },
    ],
  },
  {
    id: 'tabernacles',
    group: 'The Feasts',
    a: 'The Festival of Shelters (Sukkot)',
    b: 'God dwelling with His people',
    summary: 'Israel lived in shelters, waved palm branches, and remembered God’s care in the wilderness. On its last day Jesus cried out about living water; Revelation ends with God’s dwelling among people and palm branches before the throne.',
    rows: [
      { point: 'Living in shelters', a: ['Lev.23.42-43'], b: ['John.1.14', 'Rev.21.3'] },
      { point: 'Palm branches and rejoicing', a: ['Lev.23.40'], b: ['Rev.7.9-10', 'John.12.13'] },
      { point: 'Living water on the last day', a: ['Zech.14.8'], b: ['John.7.37-38'] },
      { point: 'All nations come to worship', a: ['Zech.14.16'], b: ['Rev.15.4'] },
    ],
  },
  {
    id: 'jubilee',
    group: 'The Feasts',
    a: 'The Year of Jubilee',
    b: 'The year of the Lord’s favor',
    summary: 'Every fiftieth year, announced by a trumpet on the Day of Atonement, debts were cancelled, slaves freed and land returned. Jesus began His ministry by proclaiming it.',
    rows: [
      { point: 'Proclaim freedom', a: ['Lev.25.10', 'Isa.61.1-2'], b: ['Luke.4.18-21'] },
      { point: 'Announced on the Day of Atonement', a: ['Lev.25.9'], b: ['Heb.9.12'] },
      { point: 'Debts cancelled', a: ['Deut.15.1-2'], b: ['Col.2.14', 'Matt.6.12'] },
      { point: 'The inheritance restored', a: ['Lev.25.13'], b: ['Acts.3.21', '1Pet.1.3-4'] },
    ],
  },

  // ---------------- Spirit & Fire ----------------
  {
    id: 'fire',
    group: 'Spirit & Fire',
    a: 'Fire falls on the sacrifice',
    b: 'Tongues of fire',
    summary: 'When God accepted the offerings at the tabernacle, the temple and Carmel, fire fell from heaven. At Pentecost the fire fell on people: living sacrifices.',
    rows: [
      { point: 'Fire at the tabernacle', a: ['Lev.9.23-24'], b: ['Acts.2.3'] },
      { point: 'Fire at the temple’s dedication', a: ['2Chr.7.1'], b: ['1Cor.3.16'] },
      { point: 'Fire on Mount Carmel', a: ['1Kgs.18.38-39'], b: ['Matt.3.11'] },
      { point: 'The fire must never go out', a: ['Lev.6.13'], b: ['Rom.12.1', 'Rom.12.11', '1Thess.5.19'] },
    ],
  },
  {
    id: 'seventy',
    group: 'Spirit & Fire',
    a: 'The Spirit on the seventy elders',
    b: 'The Spirit on all believers',
    summary: 'God put His Spirit on seventy elders and they prophesied; Moses wished all God’s people were prophets. Jesus sent out seventy (or seventy-two), and at Pentecost Moses’ wish came true.',
    rows: [
      { point: 'The Spirit shared, and they prophesy', a: ['Num.11.25'], b: ['Acts.2.4'] },
      { point: '“I wish all the LORD’s people were prophets”', a: ['Num.11.29'], b: ['Acts.2.17-18'] },
      { point: 'Seventy sent out', a: ['Num.11.16'], b: ['Luke.10.1', 'Luke.10.17'] },
    ],
  },
  {
    id: 'mantle',
    group: 'Spirit & Fire',
    a: 'Elijah taken up, Elisha receives the mantle',
    b: 'The Ascension and Pentecost',
    summary: 'Elisha had to see his master taken up to receive a double portion; the mantle fell and he did the same works. The disciples watched Jesus ascend, then received the Spirit and did greater works.',
    rows: [
      { point: 'Taken up into heaven', a: ['2Kgs.2.11'], b: ['Acts.1.9'] },
      { point: '“If you see me when I am taken…”', a: ['2Kgs.2.9-10'], b: ['Acts.1.8', 'John.16.7'] },
      { point: 'The mantle falls', a: ['2Kgs.2.13-14'], b: ['Acts.2.1-4'] },
      { point: 'A double portion: greater works', a: ['2Kgs.2.15'], b: ['John.14.12'] },
    ],
  },
  {
    id: 'babel',
    group: 'Spirit & Fire',
    a: 'Babel',
    b: 'Pentecost',
    summary: 'At Babel people tried to make a name for themselves and God confused their languages and scattered them. At Pentecost God gave languages to declare His name and gathered the nations.',
    rows: [
      { point: '“Let us make a name for ourselves”', a: ['Gen.11.4'], b: ['Acts.2.11'] },
      { point: 'Languages confused vs. languages understood', a: ['Gen.11.7'], b: ['Acts.2.6-8'] },
      { point: 'Scattered vs. gathered', a: ['Gen.11.9'], b: ['Acts.2.41', 'Rev.7.9'] },
    ],
  },
  {
    id: 'dry-bones',
    group: 'Spirit & Fire',
    a: 'The valley of dry bones',
    b: 'Breathed on and raised to life',
    summary: 'Ezekiel prophesied to the breath and the bones stood up, a vast army. Jesus breathed on His disciples, and the Spirit gives life to dead people.',
    rows: [
      { point: '“I will put breath into you”', a: ['Ezek.37.5-6'], b: ['John.20.22'] },
      { point: 'They came to life and stood up', a: ['Ezek.37.9-10'], b: ['Eph.2.4-5', 'Rom.8.11'] },
      { point: 'Graves opened', a: ['Ezek.37.12-14'], b: ['John.5.25', 'Matt.27.52'] },
    ],
  },
  {
    id: 'cloud',
    group: 'Spirit & Fire',
    a: 'The cloud of glory',
    b: 'The transfiguration and ascension',
    summary: 'God led Israel in a pillar of cloud and filled the tabernacle with it. The same cloud overshadowed the transfiguration, received Jesus at the ascension, and will accompany His return.',
    rows: [
      { point: 'The cloud leads', a: ['Exod.13.21-22'], b: ['1Cor.10.1-2'] },
      { point: 'The cloud fills the tabernacle', a: ['Exod.40.34-35'], b: ['Matt.17.5'] },
      { point: 'Taken up in a cloud', a: ['Dan.7.13'], b: ['Acts.1.9-11'] },
      { point: 'Coming on the clouds', a: ['Dan.7.13'], b: ['Rev.1.7', '1Thess.4.17'] },
    ],
  },

  // ---------------- Creation, Covenant & Bride ----------------
  {
    id: 'new-creation',
    group: 'Creation, Covenant & Bride',
    a: 'The first creation',
    b: 'The new creation',
    summary: 'Genesis opens with God, the Spirit over the waters, light, a garden, a river and the tree of life. John’s Gospel and Revelation echo each one.',
    rows: [
      { point: 'In the beginning', a: ['Gen.1.1'], b: ['John.1.1-3'] },
      { point: 'The Spirit hovering', a: ['Gen.1.2'], b: ['Luke.1.35', 'Matt.3.16'] },
      { point: '“Let there be light”', a: ['Gen.1.3'], b: ['2Cor.4.6', 'John.8.12'] },
      { point: 'God rested', a: ['Gen.2.2-3'], b: ['Heb.4.9-10'] },
      { point: 'The tree of life', a: ['Gen.2.9', 'Gen.3.22-24'], b: ['Rev.22.2', 'Rev.22.14'] },
      { point: 'A river from the garden', a: ['Gen.2.10'], b: ['Rev.22.1'] },
      { point: 'All things new', a: ['Isa.65.17'], b: ['2Cor.5.17', 'Rev.21.5'] },
    ],
  },
  {
    id: 'noah',
    group: 'Creation, Covenant & Bride',
    a: 'Noah’s ark',
    b: 'Salvation in Christ',
    summary: 'One door, one ark, rescued through water while judgment fell. Peter calls the flood a picture of baptism; Jesus says His return will be like the days of Noah.',
    rows: [
      { point: 'Found grace', a: ['Gen.6.8'], b: ['Eph.2.8'] },
      { point: 'One door', a: ['Gen.6.16'], b: ['John.10.9'] },
      { point: 'God shut them in', a: ['Gen.7.16'], b: ['John.10.28-29'] },
      { point: 'Saved through water', a: ['Gen.7.23'], b: ['1Pet.3.20-21'] },
      { point: 'The dove', a: ['Gen.8.11'], b: ['Matt.3.16'] },
      { point: 'As in the days of Noah', a: ['Gen.6.13'], b: ['Matt.24.37-39'] },
      { point: 'The rainbow covenant', a: ['Gen.9.13'], b: ['Rev.4.3'] },
    ],
  },
  {
    id: 'rebekah',
    group: 'Creation, Covenant & Bride',
    a: 'A bride for Isaac',
    b: 'The Spirit seeks a bride for the Son',
    summary: 'The father sends his servant to find a bride for his son. She receives gifts, leaves home for a groom she has not seen, and he comes out to meet her.',
    rows: [
      { point: 'The father sends a servant for the bride', a: ['Gen.24.3-4'], b: ['John.16.13-14'] },
      { point: 'Gifts given to her', a: ['Gen.24.53'], b: ['Eph.1.13-14', '1Cor.12.7'] },
      { point: '“I will go”: loving one she has not seen', a: ['Gen.24.58'], b: ['1Pet.1.8'] },
      { point: 'He comes out to meet her', a: ['Gen.24.63-64'], b: ['1Thess.4.16-17'] },
      { point: 'He loved her', a: ['Gen.24.67'], b: ['Eph.5.25'] },
    ],
  },
  {
    id: 'bride',
    group: 'Creation, Covenant & Bride',
    a: 'God and His people as husband and wife',
    b: 'The bride of Christ',
    summary: 'From Sinai on, the prophets describe God’s covenant as a marriage: He betroths, washes, clothes and rejoices over His bride, and stays faithful when she is not. The New Testament reveals the Bridegroom as Jesus and His bride as the church, made ready for the wedding of the Lamb.',
    rows: [
      { point: 'Betrothed to one husband', a: ['Jer.2.2'], b: ['2Cor.11.2'] },
      { point: '“Your Creator will be your husband”', a: ['Isa.54.5'], b: ['Eph.5.25'] },
      { point: 'He spreads His covering and makes a covenant', a: ['Ezek.16.8'], b: ['Luke.22.20'] },
      { point: 'The bride price paid', a: ['Gen.29.18-20'], b: ['Acts.20.28', '1Cor.6.19-20'] },
      { point: 'Washed and made clean', a: ['Ezek.16.9'], b: ['Eph.5.26-27'] },
      { point: 'Dressed in fine linen', a: ['Ps.45.13-14', 'Isa.61.10'], b: ['Rev.19.7-8'] },
      { point: 'The Bridegroom rejoices over His bride', a: ['Isa.62.5', 'Zeph.3.17'], b: ['John.3.29'] },
      { point: 'While the Bridegroom is with them', a: ['Hos.2.19-20'], b: ['Mark.2.19-20'] },
      { point: '“My lover is mine, and I am his”', a: ['Song.2.16'], b: ['John.10.14', 'Gal.2.20'] },
      { point: 'Love as strong as death', a: ['Song.8.6-7'], b: ['Rom.8.38-39', 'Eph.3.18-19'] },
      { point: 'Leaving her father’s house for the King', a: ['Ps.45.10-11'], b: ['Luke.14.26-27'] },
      { point: 'He brings her into his home', a: ['Gen.24.67'], b: ['John.14.2-3'] },
      { point: 'Be ready when He comes', a: ['Song.3.11'], b: ['Matt.25.1-10'] },
      { point: 'The wedding feast', a: ['Isa.25.6-8'], b: ['Matt.22.2', 'Rev.19.9'] },
      { point: 'The holy city as a bride', a: ['Isa.62.4-5'], b: ['Rev.21.2', 'Rev.21.9-10'] },
      { point: '“Come!”', a: ['Song.2.10-13'], b: ['Rev.22.17'] },
    ],
  },
  {
    id: 'eden-marriage',
    group: 'Creation, Covenant & Bride',
    a: 'The first wedding in Eden',
    b: 'The wedding of the Lamb',
    summary: 'Scripture opens with a wedding and closes with one. Paul says the union of husband and wife is a great mystery about Christ and the church.',
    rows: [
      { point: 'The two become one', a: ['Gen.2.22-24'], b: ['Eph.5.31-32'] },
      { point: 'The bride made ready', a: ['Isa.62.5'], b: ['Rev.19.7-8'] },
      { point: 'A wedding feast', a: ['Isa.25.6'], b: ['Rev.19.9', 'John.2.1-11'] },
      { point: 'The holy city as a bride', a: ['Isa.54.5'], b: ['Rev.21.2'] },
    ],
  },
  {
    id: 'sarah-hagar',
    group: 'Creation, Covenant & Bride',
    a: 'Hagar and Sarah',
    b: 'Two covenants: law and promise',
    summary: 'Paul reads Abraham’s two sons as an illustration: the son of the slave born by human effort, and the son of the free woman born by promise.',
    rows: [
      { point: 'Two sons, two mothers', a: ['Gen.16.15', 'Gen.21.2'], b: ['Gal.4.22-23'] },
      { point: 'Mount Sinai vs. the Jerusalem above', a: ['Exod.19.20'], b: ['Gal.4.24-26'] },
      { point: 'The son of the flesh mocks', a: ['Gen.21.9'], b: ['Gal.4.29'] },
      { point: 'Send away the slave', a: ['Gen.21.10'], b: ['Gal.4.30-31'] },
    ],
  },
  {
    id: 'circumcision',
    group: 'Creation, Covenant & Bride',
    a: 'Circumcision',
    b: 'Circumcision of the heart',
    summary: 'The covenant sign in the flesh always pointed to a deeper cutting away. Moses promised God would circumcise the heart; Paul says it happens in Christ.',
    rows: [
      { point: 'The covenant sign', a: ['Gen.17.10-11'], b: ['Rom.4.11'] },
      { point: 'The heart circumcised', a: ['Deut.30.6', 'Jer.4.4'], b: ['Rom.2.28-29'] },
      { point: 'A spiritual circumcision in Christ', a: ['Josh.5.2'], b: ['Col.2.11-12'] },
    ],
  },
  {
    id: 'sabbath',
    group: 'Creation, Covenant & Bride',
    a: 'The Sabbath',
    b: 'Rest in Christ',
    summary: 'God rested on the seventh day and gave Israel a day of rest. Paul calls the Sabbath a shadow; Christ is the reality, and a Sabbath rest remains for God’s people.',
    rows: [
      { point: 'God rested and blessed the day', a: ['Gen.2.2-3'], b: ['Heb.4.9-10'] },
      { point: 'Remember the Sabbath', a: ['Exod.20.8-11'], b: ['Mark.2.27-28'] },
      { point: 'A shadow of the reality', a: ['Lev.23.3'], b: ['Col.2.16-17'] },
      { point: 'Come to me and I will give you rest', a: ['Jer.6.16'], b: ['Matt.11.28-29'] },
    ],
  },
  {
    id: 'vine',
    group: 'Creation, Covenant & Bride',
    a: 'Israel the vine',
    b: 'The true vine',
    summary: 'God planted Israel as a vine that produced bitter grapes. Jesus said, “I am the true grapevine,” and fruit comes from remaining in Him.',
    rows: [
      { point: 'A vine brought out of Egypt', a: ['Ps.80.8'], b: ['John.15.1'] },
      { point: 'Looking for good grapes', a: ['Isa.5.1-2', 'Isa.5.7'], b: ['John.15.5', 'John.15.8'] },
      { point: 'Branches cut off and burned', a: ['Ezek.15.2-4'], b: ['John.15.6'] },
    ],
  },
  {
    id: 'ladder',
    group: 'Creation, Covenant & Bride',
    a: 'Jacob’s ladder',
    b: 'Jesus, the way to heaven',
    summary: 'Jacob dreamed of a stairway with angels going up and down. Jesus told Nathanael he would see angels ascending and descending on the Son of Man.',
    rows: [
      { point: 'A stairway between heaven and earth', a: ['Gen.28.12'], b: ['John.1.51'] },
      { point: 'The gateway to heaven', a: ['Gen.28.16-17'], b: ['John.14.6', 'Eph.2.18'] },
      { point: 'A new name after wrestling with God', a: ['Gen.32.27-28'], b: ['Rev.2.17', '2Cor.5.17'] },
    ],
  },
  {
    id: 'barren',
    group: 'Creation, Covenant & Bride',
    a: 'Barren women give birth',
    b: 'The virgin birth',
    summary: 'Again and again God opened closed wombs to bring the promise forward: Sarah, Rebekah, Rachel, Samson’s mother, Hannah, Elizabeth. Then a virgin conceived.',
    rows: [
      { point: 'Sarah: is anything too hard for the LORD?', a: ['Gen.18.11-14'], b: ['Luke.1.37'] },
      { point: 'Rebekah and Rachel', a: ['Gen.25.21', 'Gen.30.22'], b: ['Luke.1.7'] },
      { point: 'Samson’s mother visited by an angel', a: ['Judg.13.2-3'], b: ['Luke.1.13', 'Luke.1.26-31'] },
      { point: 'Hannah', a: ['1Sam.1.20'], b: ['Luke.1.24-25'] },
      { point: 'The virgin will conceive', a: ['Isa.7.14'], b: ['Matt.1.22-23', 'Luke.1.34-35'] },
      { point: 'Sing, barren woman', a: ['Isa.54.1'], b: ['Gal.4.27'] },
    ],
  },
  {
    id: 'hannah-mary',
    group: 'Creation, Covenant & Bride',
    a: 'Hannah’s song',
    b: 'Mary’s song',
    summary: 'Mary’s Magnificat closely echoes Hannah’s prayer: rejoicing in God’s salvation, the lowly raised, the hungry filled, and the coming king.',
    rows: [
      { point: 'My heart rejoices in the LORD', a: ['1Sam.2.1'], b: ['Luke.1.46-47'] },
      { point: 'He looked on His servant’s lowliness', a: ['1Sam.1.11'], b: ['Luke.1.48'] },
      { point: 'He lifts the poor; the rich go away empty', a: ['1Sam.2.7-8'], b: ['Luke.1.52-53'] },
      { point: 'Strength to His anointed king', a: ['1Sam.2.10'], b: ['Luke.1.32-33', 'Luke.1.69'] },
      { point: 'The boy grew in favor with God and people', a: ['1Sam.2.26'], b: ['Luke.2.52'] },
    ],
  },
  {
    id: 'mountains',
    group: 'Creation, Covenant & Bride',
    a: 'Mount Sinai',
    b: 'Mount Zion',
    summary: 'Hebrews contrasts the two mountains: fear, fire and a voice no one could bear, against the joyful city of the living God and Jesus, the mediator of a new covenant.',
    rows: [
      { point: 'Do not touch the mountain', a: ['Exod.19.12-13'], b: ['Heb.12.18-20'] },
      { point: 'Fire, darkness, trembling', a: ['Exod.19.18', 'Deut.5.25'], b: ['Heb.12.21'] },
      { point: 'You have come to Mount Zion', a: ['Ps.48.1-2'], b: ['Heb.12.22-24'] },
    ],
  },

  // ---------------- Prophecy Fulfilled ----------------
  {
    id: 'seed',
    group: 'Prophecy Fulfilled',
    a: 'The seed of the woman',
    b: 'The serpent crushed',
    summary: 'The first gospel promise: a descendant of the woman would crush the serpent’s head while His own heel was struck.',
    rows: [
      { point: 'Her offspring will crush its head', a: ['Gen.3.15'], b: ['Gal.4.4', 'Rom.16.20'] },
      { point: 'The devil’s work destroyed', a: ['Gen.3.15'], b: ['1John.3.8', 'Heb.2.14'] },
      { point: 'The dragon defeated', a: ['Gen.3.14'], b: ['Rev.12.9', 'Rev.20.10'] },
    ],
  },
  {
    id: 'lion-star',
    group: 'Prophecy Fulfilled',
    a: 'The scepter, the lion and the star',
    b: 'The King from Judah',
    summary: 'Jacob blessed Judah as a lion who would hold the scepter; Balaam saw a star rising from Jacob. Revelation names Jesus the Lion of Judah and the bright morning star.',
    rows: [
      { point: 'The lion of Judah', a: ['Gen.49.9-10'], b: ['Rev.5.5'] },
      { point: 'A star rises from Jacob', a: ['Num.24.17'], b: ['Matt.2.2', 'Rev.22.16'] },
      { point: 'A shoot from the stump of Jesse', a: ['Isa.11.1-2'], b: ['Rom.15.12', 'Rev.22.16'] },
    ],
  },
  {
    id: 'servant',
    group: 'Prophecy Fulfilled',
    a: 'The Suffering Servant',
    b: 'The Passion',
    summary: 'Written centuries before, Isaiah 53 describes a servant rejected, pierced for others’ sins, silent before His accusers, buried with the rich and raised to see His offspring.',
    rows: [
      { point: 'Despised and rejected', a: ['Isa.53.3'], b: ['John.1.11', 'Mark.15.29'] },
      { point: 'Pierced for our rebellion', a: ['Isa.53.5'], b: ['1Pet.2.24'] },
      { point: 'Silent before His accusers', a: ['Isa.53.7'], b: ['Matt.27.12-14'] },
      { point: 'Buried in a rich man’s grave', a: ['Isa.53.9'], b: ['Matt.27.57-60'] },
      { point: 'Counted among the rebels', a: ['Isa.53.12'], b: ['Mark.15.27-28', 'Luke.22.37'] },
      { point: 'Disfigured', a: ['Isa.52.14'], b: ['John.19.1-5'] },
      { point: 'He will see His offspring', a: ['Isa.53.10-11'], b: ['Acts.2.32-33'] },
    ],
  },
  {
    id: 'psalm22',
    group: 'Prophecy Fulfilled',
    a: 'Psalm 22',
    b: 'The cross',
    summary: 'David’s psalm of abandonment reads like an eyewitness account of the crucifixion, and Jesus prayed its opening line from the cross.',
    rows: [
      { point: '“My God, my God, why have you abandoned me?”', a: ['Ps.22.1'], b: ['Matt.27.46'] },
      { point: 'Mocked: “Let the LORD rescue him!”', a: ['Ps.22.7-8'], b: ['Matt.27.39-43'] },
      { point: 'Thirst', a: ['Ps.22.15'], b: ['John.19.28'] },
      { point: 'Hands and feet pierced', a: ['Ps.22.16'], b: ['John.20.25'] },
      { point: 'They gamble for His clothing', a: ['Ps.22.18'], b: ['John.19.23-24'] },
      { point: 'Praise among His brothers', a: ['Ps.22.22'], b: ['Heb.2.11-12'] },
      { point: '“He has done it”', a: ['Ps.22.31'], b: ['John.19.30'] },
    ],
  },
  {
    id: 'zechariah',
    group: 'Prophecy Fulfilled',
    a: 'Zechariah’s shepherd-king',
    b: 'Holy Week',
    summary: 'Zechariah foresaw the humble king on a donkey, thirty pieces of silver thrown to the potter, the pierced one mourned, and the shepherd struck as the sheep scatter.',
    rows: [
      { point: 'Your king comes on a donkey', a: ['Zech.9.9'], b: ['Matt.21.4-5'] },
      { point: 'Thirty pieces of silver for the potter', a: ['Zech.11.12-13'], b: ['Matt.27.3-10'] },
      { point: 'Strike the shepherd; the sheep scatter', a: ['Zech.13.7'], b: ['Matt.26.31', 'Matt.26.56'] },
      { point: 'They will look on the one they pierced', a: ['Zech.12.10'], b: ['John.19.37', 'Rev.1.7'] },
    ],
  },
  {
    id: 'daniel-den',
    group: 'Prophecy Fulfilled',
    a: 'Daniel in the lions’ den',
    b: 'The sealed tomb',
    summary: 'A blameless man condemned by jealous officials, sealed in with a stone and the king’s signet, found alive at dawn.',
    rows: [
      { point: 'No fault could be found', a: ['Dan.6.4'], b: ['Luke.23.4', 'John.18.38'] },
      { point: 'A stone sealed over the opening', a: ['Dan.6.17'], b: ['Matt.27.66'] },
      { point: 'At first light, hurrying to the place', a: ['Dan.6.19-20'], b: ['Mark.16.2'] },
      { point: 'Alive; an angel sent', a: ['Dan.6.22'], b: ['Matt.28.2-6'] },
      { point: 'The accusers fall', a: ['Dan.6.24'], b: ['Col.2.15'] },
    ],
  },
  {
    id: 'furnace',
    group: 'Prophecy Fulfilled',
    a: 'The fourth man in the fire',
    b: 'Christ with us in the fire',
    summary: 'Three faithful men were thrown into the furnace, and the king saw a fourth walking with them. They came out without even the smell of smoke.',
    rows: [
      { point: 'Faith whether or not God rescues', a: ['Dan.3.17-18'], b: ['Heb.11.33-34'] },
      { point: 'A fourth man in the fire', a: ['Dan.3.25'], b: ['Matt.28.20', 'Heb.13.5'] },
      { point: 'When you walk through the fire', a: ['Isa.43.2'], b: ['1Pet.4.12-13'] },
      { point: 'Not even the smell of smoke', a: ['Dan.3.27'], b: ['1Pet.1.7'] },
    ],
  },
  {
    id: 'shepherd',
    group: 'Prophecy Fulfilled',
    a: 'The LORD my shepherd',
    b: 'The good shepherd',
    summary: 'God promised to shepherd His scattered flock Himself and set one shepherd, David, over them. Jesus said, “I am the good shepherd.”',
    rows: [
      { point: 'The LORD is my shepherd', a: ['Ps.23.1'], b: ['John.10.11', 'John.10.14'] },
      { point: 'I Myself will search for My sheep', a: ['Ezek.34.11-12'], b: ['Luke.19.10', 'Luke.15.4-6'] },
      { point: 'One shepherd from David’s line', a: ['Ezek.34.23'], b: ['John.10.16', 'Heb.13.20'] },
      { point: 'He carries the lambs', a: ['Isa.40.11'], b: ['1Pet.2.25', '1Pet.5.4'] },
    ],
  },
  {
    id: 'lot',
    group: 'Prophecy Fulfilled',
    a: 'Sodom and Lot',
    b: 'The day the Son of Man is revealed',
    summary: 'Jesus used Lot’s rescue from Sodom as a picture of His return: life going on as usual, sudden judgment, and a warning not to look back.',
    rows: [
      { point: 'Life as usual, then sudden judgment', a: ['Gen.19.24-25'], b: ['Luke.17.28-30'] },
      { point: 'Hurried out before the fire fell', a: ['Gen.19.15-17'], b: ['2Pet.2.6-9'] },
      { point: 'Remember Lot’s wife', a: ['Gen.19.26'], b: ['Luke.17.31-33'] },
    ],
  },
  {
    id: 'enoch',
    group: 'Prophecy Fulfilled',
    a: 'Enoch taken up',
    b: 'Caught up to meet the Lord',
    summary: 'Enoch walked with God and was gone, because God took him. Hebrews says he was taken without dying; Paul describes believers caught up to meet the Lord.',
    rows: [
      { point: 'Walked with God, then taken', a: ['Gen.5.24'], b: ['Heb.11.5'] },
      { point: 'Caught up', a: ['Gen.5.24'], b: ['1Thess.4.16-17'] },
      { point: 'Enoch prophesied His coming', a: ['Enoch.1.9'], b: ['Jude.1.14-15'] },
    ],
  },
]

export const patternById = Object.fromEntries(PATTERNS.map((p) => [p.id, p]))
